# Generated by Django 4.2.5 on 2023-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
